### ISSUE TITLE
Посмотрите в перегруженный метод с BeanDefinitionCustomizer, и там добавляйте property c ${} через getPropertyValues

### ISSUE THREAD

**Issue by coursar** [KartonDCP/ConfigurationWithDI#1]
https://github.com/KartonDCP/ConfigurationWithDI/blob/12e802a0f8ea2fca9214949137cb1535f22277f8/src/test/java/org/example/datasources/ProgrammicRegistrationTest.java#L27-L41

**Comment by KartnDev** [comment]
@coursar  я увидел `contstructorArgs`с и `RuntimeBeanReference` - меньше кода и понятнее, чем `getPropertyValues`

**Comment by coursar** [comment]
Это в лекции была подсказка, да ))
