### ISSUE TITLE
Зачем два-то?

### ISSUE THREAD

**Issue by coursar** [KartonDCP/ConfigurationWithDI#4]
https://github.com/KartonDCP/ConfigurationWithDI/blob/12e802a0f8ea2fca9214949137cb1535f22277f8/src/main/java/org/example/javaconfiguration/ConnectionConfiguration.java#L21-L32

**Comment by KartnDev** [comment]
Просто хотелось самому проверить DI внутри конфигурационного класса, что Spring при вызове `sqLiteDataSource()` дейстивительно будет это дело проксировать и возвращать Spring Bean из `SingletonObjects`
@coursar  Так вроде все пофиксил
